general.import = ["tokyo_night_theme.toml"]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Fond" , style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 11

[keyboard]
bindings = [
    { key = "Insert", mods = "Shift", action = "Paste" },
    { key = "Insert", mods = "Control" , action = "Copy" },
    { key = "F11" , action = "ToggleFullscreen" }
]

[scrolling]
history = 50000

[window]
opacity = 1.0
padding.x = 14
paddin.y = 14
blur = false
decorations= "Buttonless"
# option_as_alt = "Both"
