- name: Install hyprland packages
  community.general.yay:
    name:
     - hyprland  # Tiling window manager
     - hyprshot  # Take screenshots
     - hyprpicker  # Color picker
     - hyprlock  # Lock screen
     - hypridle  # Idle after certain time
     - hyprsunset  # To set nigthmode
     - polkit-gnome  # Auth agent
     - hyprland-qtutils  # Qt apps integration
     - walker-bin  # App launcher
     - wofi  # App launcher
     - libqalculate  # Math
     - waybar  # Status bar
     - mako  # Notifications daemon
     - swaybg  # Set wallpaper
     - swayosd  # OSD server to show volume, bright indications
     - xdg-desktop-portal-hyprland
     - xdg-desktop-portal-gtk
     - uwsm
     - xdg-terminal-exec