- name: Update pacman
  pacman:
    update_cache: yes

- name: Install dependencies for yay
  pacman:
    name:
      - git
      - base-devel

- name: Clone yay repository
  become: yes
  git:
    repo: https://aur.archlinux.org/yay-git.git
    dest: /opt/yay-git
    clone: yes
    update: no

- name: Change yay directory ownership
  become: yes
  file:
    path: /opt/yay-git
    owner: "{{ user }}"
    group: "{{ user }}"
    recurse: yes

- name: Install yay
  become: yes
  become_user: "{{ user }}"
  command: makepkg -si --noconfirm
  args:
    chdir: /opt/yay-git
