- name: Install fonts
  pacman:
    name:
      - ttf-font-awesome
      - ttf-cascadia-mono-nerd
      - noto-fonts
      - noto-fonts-emoji
      - ttf-jetbrains-mono-nerd
      - noto-fonts-cjk
      - noto-fonts-extra
      - ttf-ia-writer
      - woff2-font-awesome
      - fontconfig